name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main  # ya 'master' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Navigate to frontend
        run: cd frontend

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build Vite App
        run: |
          cd frontend
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/dist
 